# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      APP_ENV: prod
      APP_SECRET: c4136a0540553455b122461ab6923e9d
      WKHTMLTOPDF_PATH: wkhtmltopdf
      CLIENT_TOKEN: 123456
      SOL_USER: 20161515648MODDATOS
      SOL_PASS: MODDATOS
      CORS_ALLOW_ORIGIN: .
      TRUSTED_PROXIES: "127.0.0.1,REMOTE_ADDR"
    # depends_on:
    #   - nginx
  ngnix:
    image: nginx:alpine
    ports:
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app